### ISSUE TITLE
Plano de riscos

### ISSUE THREAD

**Issue by JoaoHenrique12** [UnBArqDsw2022-2/2022.2_G3_SpotHood#3]
### Summary

Crie um plano de riscos, custos e tempo, adicione-o na pasta assets.

### Motivation

Gerenciar o projeto.

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by Rocsantos** [comment]
Foi adicionadoo plano de riscos [](https://github.com/UnBArqDsw2022-2/2022.2_G3_SpotHood/tree/74c71678ef90c5016246ffe56036fa7932e9649b).
Onde há Introdução, Processo do Gerenciamento, Categoria de Riscos, Matriz de Impactos e Riscos

**Comment by Rocsantos** [comment]
Foi Adicionado [Estrutura Análitica do Gerenciamento de Projeto](https://github.com/UnBArqDsw2022-2/2022.2_G3_SpotHood/commit/5982955092f761b55f959428cb6095f7af8e11e9).

**Comment by Rocsantos** [comment]
Foi feito correções de normas ABNT, em citações, legendas de imagem e tabelas por mim(@Rocsantos) e por (@MarianaPRio)
