### ISSUE TITLE
Prototipaçao inicial da aplicação

### ISSUE THREAD

**Issue by yukioz** [UnBArqDsw2022-2/2022.2_G3_SpotHood#8]
### Summary

# Descrição:

Iniciar prototipação das primeiras páginas do projeto. O modelo deve ser feito no figma e conter página de login, home page e criar/adicionar usuários.

### Motivation

Auxiliar na construção de um modelo com boa usabilidade para o usuário.

### Alternatives

desenho/esboço no papel como protótipo de baixa fidelidade.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by viniciused26** [comment]
Protótipo finalizado, imagens estão na pasta assets/prototype e no DesignSprint.md está o fluxo com o protótipo funcionando (com ajuda do @Rocsantos).
